[package]
name = "meme_lending_pinocchio"
version = "0.1.0"
description = "Optimized Pinocchio implementation of Meme Lend"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "meme_lending_pinocchio"

[features]
default = []
bpf-entrypoint = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[dependencies]
pinocchio = { version = "0.11.0", default-features = false, features = ["cpi"] }
pinocchio-system = "0.6.1"
pinocchio-token = "0.7.0"
pinocchio-token-2022 = "0.4.0"
solana-security-txt = "1.1.3"
solana-address = { version = "2.7.0", features = ["curve25519", "sha2", "syscalls"] }
